// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPriceRequest) Reset() {
	*x = FetchPriceRequest{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPriceRequest) ProtoMessage() {}

func (x *FetchPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPriceRequest.ProtoReflect.Descriptor instead.
func (*FetchPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *FetchPriceRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type FetchPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPriceResponse) Reset() {
	*x = FetchPriceResponse{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPriceResponse) ProtoMessage() {}

func (x *FetchPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPriceResponse.ProtoReflect.Descriptor instead.
func (*FetchPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *FetchPriceResponse) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *FetchPriceResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type StreamPricesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tickers         []string               `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamPricesRequest) Reset() {
	*x = StreamPricesRequest{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPricesRequest) ProtoMessage() {}

func (x *StreamPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPricesRequest.ProtoReflect.Descriptor instead.
func (*StreamPricesRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *StreamPricesRequest) GetTickers() []string {
	if x != nil {
		return x.Tickers
	}
	return nil
}

func (x *StreamPricesRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type StreamPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPricesResponse) Reset() {
	*x = StreamPricesResponse{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPricesResponse) ProtoMessage() {}

func (x *StreamPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPricesResponse.ProtoReflect.Descriptor instead.
func (*StreamPricesResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *StreamPricesResponse) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *StreamPricesResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StreamPricesResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\"+\n" +
	"\x11FetchPriceRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\"B\n" +
	"\x12FetchPriceResponse\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\"Z\n" +
	"\x13StreamPricesRequest\x12\x18\n" +
	"\atickers\x18\x01 \x03(\tR\atickers\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\"b\n" +
	"\x14StreamPricesResponse\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp2\x84\x01\n" +
	"\fPriceFetcher\x125\n" +
	"\n" +
	"FetchPrice\x12\x12.FetchPriceRequest\x1a\x13.FetchPriceResponse\x12=\n" +
	"\fStreamPrices\x12\x14.StreamPricesRequest\x1a\x15.StreamPricesResponse0\x01B8Z6github.com/aliaksandrp/microservice-priceFetcher/protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_service_proto_goTypes = []any{
	(*FetchPriceRequest)(nil),    // 0: FetchPriceRequest
	(*FetchPriceResponse)(nil),   // 1: FetchPriceResponse
	(*StreamPricesRequest)(nil),  // 2: StreamPricesRequest
	(*StreamPricesResponse)(nil), // 3: StreamPricesResponse
}
var file_proto_service_proto_depIdxs = []int32{
	0, // 0: PriceFetcher.FetchPrice:input_type -> FetchPriceRequest
	2, // 1: PriceFetcher.StreamPrices:input_type -> StreamPricesRequest
	1, // 2: PriceFetcher.FetchPrice:output_type -> FetchPriceResponse
	3, // 3: PriceFetcher.StreamPrices:output_type -> StreamPricesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
